connect form to server and fix validation issues
yaay/youth-parliment pull request #14
Opened 2023-12-21 13:35 UTC by yaay

2023-12-25 05:28 UTC, Tasneem-Gad requested changes

2023-12-25 05:28 UTC, Tasneem-Gad commented on src/app/domain/basic-information/models/basic-information.ts
> +    "version": number,
we do not need to send or show the version  in ui

2023-12-25 05:28 UTC, Tasneem-Gad commented on src/app/domain/basic-information/models/basic-information.ts
> +    "birthDate": string,
why add a property in double quotation?

2023-12-25 05:28 UTC, Tasneem-Gad commented on src/app/domain/basic-information/models/basic-information.ts
> +    "request": {
why not separate in another interface

2023-12-25 05:28 UTC, Tasneem-Gad commented on src/app/domain/basic-information/models/basic-information.ts
> +        "requestStatus": any,
don't use any

2023-12-25 05:28 UTC, Tasneem-Gad commented on src/app/domain/basic-information/request-basic-information.repository.ts
> +    addBasicInformation(id: number, resource: any): Observable<any> {
don't use any

2023-12-25 05:28 UTC, Tasneem-Gad commented on src/app/domain/basic-information/request-basic-information.repository.ts
> +        formattedResource['birthDate'] = formattedResource.dob?.year + '-' + formattedResource.dob?.month + '-' + formattedResource.dob?.day;
why add this validation here?

2023-12-25 05:28 UTC, Tasneem-Gad commented on src/app/pages/form-stepper/pages/main-data/main-data.component.ts
> +  disabilityTypeShow() {
try naming be meaningful

2023-12-25 05:28 UTC, Tasneem-Gad commented on src/app/pages/form-stepper/pages/main-data/main-data.component.ts
>      this.eduAdminRepository.getEducationsAdministration(govId).subscribe((response: any) => {
don't use any

2023-12-25 05:28 UTC, Tasneem-Gad commented on src/app/pages/form-stepper/pages/main-data/main-data.component.ts
>      this.clubRepository.getClubs(govId).subscribe((response: any) => {
same

2023-12-25 05:28 UTC, Tasneem-Gad commented on src/app/domain/basic-information/basic-information.repository.ts
> +        let formattedResource = this.extractIds.extractIds(resource);
why make validation here

2023-12-25 10:51 UTC, Rawan2211 approved these changes

2023-12-31 13:34 UTC, Tasneem-Gad requested changes

2023-12-31 13:34 UTC, Tasneem-Gad commented on src/app/pages/form-stepper/pages/main-data/main-data.component.ts
> +    // console.log('cdr')
remove

2024-01-02 10:16 UTC, Rawan2211 approved these changes

2024-01-08 12:49 UTC, merged